name: generate-snake

on:
  # Manually run the job at any time
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Run Platane/snk action to generate snake game SVG
      - name: Generate snake game
        uses: Platane/snk@v4
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
